WIDTH=9
HEIGHT=7

┌───────┐
│2  ♠   │
│       │
│       │
│       │
│   ♠  ↊│
└───────┘
┌───────┐
│3  ♠   │
│       │
│   ♠   │
│       │
│   ♠  ↋│
└───────┘
┌───────┐
│4♠   ♠ │
│       │
│       │
│       │
│ ♠   ♠h│
└───────┘
┌───────┐
│5♠   ♠ │
│       │
│   ♠   │
│       │
│ ♠   ♠ϛ│
└───────┘
┌───────┐
│6♠   ♠ │
│       │
│ ♠   ♠ │
│       │
│ ♠   ♠9│
└───────┘
┌───────┐
│7♠   ♠ │
│   ♠   │
│ ♠   ♠ │
│       │
│ ♠   ♠L│
└───────┘
┌───────┐
│8♠   ♠ │
│   ♠   │
│ ♠   ♠ │
│   ♠   │
│ ♠   ♠8│
└───────┘
┌───────┐
│9  ♠   │
│ ♠ ♠ ♠ │
│   ♠   │
│ ♠ ♠ ♠ │
│   ♠  6│
└───────┘
┌───────┐
│10 ♠   │
│ ♠ ♠ ♠ │
│ ♠   ♠ │
│ ♠ ♠ ♠ │
│   ♠ 0Ɩ│
└───────┘
┌───────┐
│J‿‿‿‿‿ │
│♠\˅│˅/ │
│ └──˄┘ │
│  (‿⋏‿)│
│    ┴ Ր│
└───────┘
┌───────┐
│Q ⋏‡⋏  │
│♠﴾ʬӜʬ﴿ │
│ └──˄┘ │
│  (‿⋏‿)│
│    ┴ Ծ│
└───────┘
┌───────┐
│Kₒ⋏ₒ⋏ₒ │
│♠\˅│˅/ │
│ └──˄┘ │
│  (‿⋏‿)│
│    ┴ Ʞ│
└───────┘
┌───────┐
│ᗅ      │
│♠  ˄   │
│ (‿⋏‿) │
│   ┴   │
│      ᗄ│
└───────┘
┌───────┐
│2  ♣   │
│       │
│       │
│       │
│   ♣  ↊│
└───────┘
┌───────┐
│3  ♣   │
│       │
│   ♣   │
│       │
│   ♣  ↋│
└───────┘
┌───────┐
│4♣   ♣ │
│       │
│       │
│       │
│ ♣   ♣h│
└───────┘
┌───────┐
│5♣   ♣ │
│       │
│   ♣   │
│       │
│ ♣   ♣ϛ│
└───────┘
┌───────┐
│6♣   ♣ │
│       │
│ ♣   ♣ │
│       │
│ ♣   ♣9│
└───────┘
┌───────┐
│7♣   ♣ │
│   ♣   │
│ ♣   ♣ │
│       │
│ ♣   ♣L│
└───────┘
┌───────┐
│8♣   ♣ │
│   ♣   │
│ ♣   ♣ │
│   ♣   │
│ ♣   ♣8│
└───────┘
┌───────┐
│9  ♣   │
│ ♣ ♣ ♣ │
│   ♣   │
│ ♣ ♣ ♣ │
│   ♣  6│
└───────┘
┌───────┐
│10 ♣   │
│ ♣ ♣ ♣ │
│ ♣   ♣ │
│ ♣ ♣ ♣ │
│   ♣ 0Ɩ│
└───────┘
┌───────┐
│J‿‿‿‿‿ │
│♣\˅│˅/ │
│ └─(⁀) │
│  (‿˅‿)│
│    ┴ Ր│
└───────┘
┌───────┐
│Q ⋏‡⋏  │
│♣﴾ʬӜʬ﴿ │
│ └─(⁀) │
│  (‿˅‿)│
│    ┴ Ծ│
└───────┘
┌───────┐
│Kₒ⋏ₒ⋏ₒ │
│♣\˅│˅/ │
│ └─(⁀) │
│  (‿˅‿)│
│    ┴ Ʞ│
└───────┘
┌───────┐
│ᗅ      │
│♣ (⁀)  │
│ (‿˅‿) │
│   ┴   │
│      ᗄ│
└───────┘
┌───────┐
│2  ♥   │
│       │
│       │
│       │
│   ♥  ↊│
└───────┘
┌───────┐
│3  ♥   │
│       │
│   ♥   │
│       │
│   ♥  ↋│
└───────┘
┌───────┐
│4♥   ♥ │
│       │
│       │
│       │
│ ♥   ♥h│
└───────┘
┌───────┐
│5♥   ♥ │
│       │
│   ♥   │
│       │
│ ♥   ♥ϛ│
└───────┘
┌───────┐
│6♥   ♥ │
│       │
│ ♥   ♥ │
│       │
│ ♥   ♥9│
└───────┘
┌───────┐
│7♥   ♥ │
│   ♥   │
│ ♥   ♥ │
│       │
│ ♥   ♥L│
└───────┘
┌───────┐
│8♥   ♥ │
│   ♥   │
│ ♥   ♥ │
│   ♥   │
│ ♥   ♥8│
└───────┘
┌───────┐
│9  ♥   │
│ ♥ ♥ ♥ │
│   ♥   │
│ ♥ ♥ ♥ │
│   ♥  6│
└───────┘
┌───────┐
│10 ♥   │
│ ♥ ♥ ♥ │
│ ♥   ♥ │
│ ♥ ♥ ♥ │
│   ♥ 0Ɩ│
└───────┘
┌───────┐
│J‿‿‿‿‿ │
│♥\˅│˅/ │
│ └(⁀˅⁀)│
│   \ / │
│    ˅ Ր│
└───────┘
┌───────┐
│Q ⋏‡⋏  │
│♥﴾ʬӜʬ﴿ │
│ └(⁀˅⁀)│
│   \ / │
│    ˅ Ծ│
└───────┘
┌───────┐
│Kₒ⋏ₒ⋏ₒ │
│♥\˅│˅/ │
│ └(⁀˅⁀)│
│   \ / │
│    ˅ Ʞ│
└───────┘
┌───────┐
│ᗅ      │
│♥(⁀˅⁀) │
│  \ /  │
│   ˅   │
│      ᗄ│
└───────┘
┌───────┐
│2  ♦   │
│       │
│       │
│       │
│   ♦  ↊│
└───────┘
┌───────┐
│3  ♦   │
│       │
│   ♦   │
│       │
│   ♦  ↋│
└───────┘
┌───────┐
│4♦   ♦ │
│       │
│       │
│       │
│ ♦   ♦h│
└───────┘
┌───────┐
│5♦   ♦ │
│       │
│   ♦   │
│       │
│ ♦   ♦ϛ│
└───────┘
┌───────┐
│6♦   ♦ │
│       │
│ ♦   ♦ │
│       │
│ ♦   ♦9│
└───────┘
┌───────┐
│7♦   ♦ │
│   ♦   │
│ ♦   ♦ │
│       │
│ ♦   ♦L│
└───────┘
┌───────┐
│8♦   ♦ │
│   ♦   │
│ ♦   ♦ │
│   ♦   │
│ ♦   ♦8│
└───────┘
┌───────┐
│9  ♦   │
│ ♦ ♦ ♦ │
│   ♦   │
│ ♦ ♦ ♦ │
│   ♦  6│
└───────┘
┌───────┐
│10 ♦   │
│ ♦ ♦ ♦ │
│ ♦   ♦ │
│ ♦ ♦ ♦ │
│   ♦ 0Ɩ│
└───────┘
┌───────┐
│J‿‿‿‿‿ │
│♦\˅│˅/ │
│ └──˄┘ │
│   ( ) │
│    ˅ Ր│
└───────┘
┌───────┐
│Q ⋏‡⋏  │
│♦﴾ʬӜʬ﴿ │
│ └──˄┘ │
│   ( ) │
│    ˅ Ծ│
└───────┘
┌───────┐
│Kₒ⋏ₒ⋏ₒ │
│♦\˅│˅/ │
│ └──˄┘ │
│   ( ) │
│    ˅ Ʞ│
└───────┘
┌───────┐
│ᗅ      │
│♦  ˄   │
│  ( )  │
│   ˅   │
│      ᗄ│
└───────┘